# Generated by Django 2.1.3 on 2018-11-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('university', models.CharField(choices=[('kntu', 'KNTU'), ('ksu', 'KSU'), ('ksau', 'KSAU'), ('kma', 'KMA')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
